-- MySQL Script generated by MySQL Workbench
-- Fri Aug 28 11:13:15 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Friends
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Friends
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Friends` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Friends` ;

-- -----------------------------------------------------
-- Table `Friends`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Friends`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `alias` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `birth_date` DATE NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Friends`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Friends`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `friend_id` INT NOT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_friends_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_friends_users2_idx` (`friend_id` ASC)  COMMENT '',
  CONSTRAINT `fk_friends_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Friends`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friends_users2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `Friends`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Friends` ;

-- -----------------------------------------------------
-- Placeholder table for view `Friends`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Friends`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `Friends`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Friends`.`view1`;
USE `Friends`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
